compiler_command = "tools/gcc_kmc/gcc -Iinclude -Ilib/ultralib/include -c -O2 -mips3 -mgp32 -mfp32 -mno-abicalls -G0 -fno-common -fno-builtin -B tools/gcc_kmc/ -DPERMUTER"

assembler_command = "mips-linux-gnu-as -EB -march=vr4300 -mtune=vr4300 -Iinclude"

compiler_type = "gcc"

[preserve_macros]
"g[DS]P.*" = "void"
"gs[DS]P.*" = "void"
"G_.*" = "void"
