#include "common.h"

void cutsceneEffectDisp_init(void);
s32 cutsceneEffectDisp_validate(void);
void cutsceneEffectDisp_exec(void);
s32 cutsceneEffectDisp_isDone(void);
void cutsceneEffectFan_init(void);
s32 cutsceneEffectFan_validate(void);
void cutsceneEffectFan_exec(void);
s32 cutsceneEffectFan_isDone(void);
void cutsceneEffectRocket_init(void);
s32 cutsceneEffectRocket_validate(void);
void cutsceneEffectRocket_exec(void);
s32 cutsceneEffectRocket_isDone(void);
void cutsceneEffectMLight_init(void);
s32 cutsceneEffectMLight_validate(void);
void cutsceneEffectMLight_exec(void);
void cutsceneEffectTrick_init(void);
s32 cutsceneEffectTrick_validate(void);
void cutsceneEffectTrick_exec(void);
void cutsceneEffectTrick_update(void);
s32 cutsceneEffectTrick_isDone(void);
void cutsceneInitTrack_init(void);
s32 cutsceneInitTrack_validate(void);
void cutsceneInitTrack_exec(void);