#!/usr/bin/env python3
from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from tools.course_assets_common import iter_course_manifests, load_yaml, pack_track_sector_mesh, parse_int


def macro_name(name: str) -> str:
    return f"{name}_DECOMPRESSED_SIZE"


def manifest_size(path: Path, manifest: dict) -> int:
    if manifest.get("format") == "track_sector_mesh":
        return len(pack_track_sector_mesh(manifest))
    return parse_int(manifest["decompressed_size"])


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate course asset decompressed size macros.")
    parser.add_argument("--assets-root", type=Path, default=Path("assets/courses"))
    parser.add_argument("--out", type=Path, required=True)
    args = parser.parse_args()

    lines = [
        "#pragma once",
        "",
        "/* Auto-generated by tools/course_asset_sizes.py. */",
        "",
    ]
    for path in iter_course_manifests(args.assets_root):
        manifest = load_yaml(path)
        name = str(manifest["name"])
        lines.append(f"#define {macro_name(name)} 0x{manifest_size(path, manifest):X}")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
